title: 0-days In-the-Wild
author: Google Project Zero
email: 0day-in-the-wild@google.com
description: Information about 0-days exploited in-the-wild!
github_username:  googleprojectzero
repository: googleprojectzero/0days-in-the-wild

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
- 
  scope:
          path: "0day-RCAs"
  values:
          category: "rca"
