title: 0-days In-the-Wild
author: Google Project Zero
email: 0day-in-the-wild@google.com
description: Information about 0-days exploited in-the-wild!
github_username:  googleprojectzero

# Build settings
theme: minima
plugins:
  - jekyll-feed
repository: googleprojectzero/0days-in-the-wild

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
