menu:
- {name: 'Root Cause Analyses', url: 'rca.html'}
- {name: 'Tracking Sheet', url: 'https://docs.google.com/spreadsheets/d/1lkNJ0uQwbeC1ZTRrxdtuPLCIl7mlUreoKfSIgajnSyY'}
- {name: 'Contributing', url: 'contributing.html'}
- {name: 'About', url: 'about.html'}

social:
- {icon: 'fab fa-blogger', link: 'https://googleprojectzero.blogspot.com/'}
- {icon: 'fas fa-bug', link: 'https://bugs.chromium.org/p/project-zero/issues/list'}
- {icon: 'fab fa-github', link: 'https://github.com/googleprojectzero/0days-in-the-wild'}
- {icon: 'fas fa-envelope', link: 'mailto:0day-in-the-wild@google.com'}

